### ISSUE TITLE
[Feature Request]:  PAPI support

### ISSUE THREAD

**Issue by neviskcubo** [Crazy-Crew/CrazyVouchers#45] opened 2024-04-12 03:19 UTC
### Describe the feature

Possibility of adding placeholders to the name/lore of vouchers.

Example:

lore:
- 'Awarded: %player_name%'

It would return the nick of the player who received that voucher...

**Comment by ryderbelserion** [comment] 2024-04-13 18:50
Duplicate of https://github.com/Crazy-Crew/CrazyVouchers/issues/43

**Closed by ryderbelserion** 2024-04-13 18:50 UTC
